[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=384"
PORT = "3777"

[phases.build]
cmds = ["NODE_OPTIONS='--max-old-space-size=450' npm run build:all"]

[start]
cmd = "node --expose-gc --max-old-space-size=384 dist/index.js"
